services:
  api:
    container_name: shortly_server
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    container_name: shortly_pg_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      

  redis:
    image: redis:7
    container_name: shortly_redis
    ports:
      - "6379:6379"


volumes:
  pgdata: